// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20210820214244_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 1,
                            Gender = "Female",
                            Name = "Fifi",
                            Species = "Holland Lop"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 1,
                            Gender = "Unknown",
                            Name = "Bobo",
                            Species = "Lizard"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 1,
                            Gender = "Female",
                            Name = "Smol",
                            Species = "Holland Lop"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 1,
                            Gender = "Male",
                            Name = "vSmol",
                            Species = "Holland Lop"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            Gender = "Male",
                            Name = "Gus",
                            Species = "Holland Lop"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 3,
                            Gender = "Female",
                            Name = "Commando",
                            Species = "Holland Lop"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 1,
                            Gender = "Unknown",
                            Name = "Bubba",
                            Species = "Lizard"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 1,
                            Gender = "Female",
                            Name = "The Onion",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 1,
                            Gender = "Male",
                            Name = "Big Nose",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 2,
                            Gender = "Male",
                            Name = "Hungry",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 3,
                            Gender = "Female",
                            Name = "Muffin",
                            Species = "Holland Lop"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 1,
                            Gender = "Unknown",
                            Name = "Dumbo",
                            Species = "Holland Lop"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 1,
                            Gender = "Female",
                            Name = "Potato",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 1,
                            Gender = "Unknown",
                            Name = "Matchstick",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 1,
                            Gender = "Male",
                            Name = "Orion",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 16,
                            Age = 3,
                            Gender = "Female",
                            Name = "Peggy",
                            Species = "Holland Lop"
                        },
                        new
                        {
                            AnimalId = 17,
                            Age = 1,
                            Gender = "Unknown",
                            Name = "Herb",
                            Species = "Holland Lop"
                        },
                        new
                        {
                            AnimalId = 18,
                            Age = 1,
                            Gender = "Male",
                            Name = "Kevin",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 19,
                            Age = 1,
                            Gender = "Male",
                            Name = "Daniel",
                            Species = "Bunny"
                        },
                        new
                        {
                            AnimalId = 20,
                            Age = 2,
                            Gender = "Male",
                            Name = "Steve",
                            Species = "Bunny"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
